version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: georgryabov
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=georgryabov
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=database
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
